version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'nuget'
    directory: '/'
    schedule:
      interval: 'daily'

  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Enable version updates for Docker
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'